### ISSUE TITLE
Restore Nuget Packge Failed

### ISSUE THREAD

**Issue by ravisolanki07** [charlenni/Mapsui.VectorTiles#2]
After downloading the repository, I tried to restore (not updating) all the nuget packages using VS2017. But I am getting following error:
![IssueMap](https://user-images.githubusercontent.com/31103762/54604315-761c4b80-4a6c-11e9-84f7-c60409b41122.PNG)

Please help me!

**Comment by charlenni** [comment]
Try to use the normal Mapsui package instead of the beta version I used at the time, I created the repository.

**Comment by ravisolanki07** [comment]
Thanks for your quick reply.

I tried to update the MapSui package alone, but it's still not allowing me to update it.

**Comment by charlenni** [comment]
What do you mean with "still not allowing me to update it"? Any error messages?

**Comment by ravisolanki07** [comment]
So let me tell you the steps that I am doing:
1. Manage Nuget Packages for the Solution
2. Select MapSui - this way it will show all the projects 
![IssueMap](https://user-images.githubusercontent.com/31103762/54613461-beddff80-4a80-11e9-85b2-b5e24578355c.PNG)
3. Then I tried to Install the new latest version of it. And it gives the error which you can see in the screenshot.

FYI, I have tried to install the new as well as an old version of the MapSui.

Thanks!

**Comment by charlenni** [comment]
Try to remove all occurrences of Mapsui and add them again to the projects.

**Comment by ravisolanki07** [comment]
Thanks for your suggestion! That really eliminates most of the errors. 

I am still facing the following errors:
![IssueMap](https://user-images.githubusercontent.com/31103762/54626457-33239d80-4a97-11e9-8b9f-a344a5ca5a28.PNG)

I believe these errors are related to versions of the packages.
Could you please help me?

**Comment by charlenni** [comment]
It seems, that you are missing the NuGet package for BruTile.

**Comment by ravisolanki07** [comment]
Thank you for your quick reply.

I already added all the plugins that include BruTile(1.0.2). 

![image](https://user-images.githubusercontent.com/31103762/54657081-1070a380-4aee-11e9-995d-8eca0785814d.png)

**Comment by charlenni** [comment]
I tried to get, what was going on a year ago and I think, I dropped the development of this project and moved on to integrate it into Mapsui. So it seems, that you should use the [VectorTiles](https://github.com/charlenni/Mapsui/tree/VectorTiles) branch of Mapsui in my repositories. 

Sorry, that I remember this not before.

**Comment by ravisolanki07** [comment]
Thanks for your guidance, I will do that.
